[package]
name = "bpsr-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
tauri = { version = "2.10.2", features = [] }

[build-dependencies]
tauri-build = { version = "2.5.5", features = [] }
